mysql:
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: fsjs_sql_server
  username: root
  password: "root"
  path: 127.0.0.1
  max-idle-conns: 100
  max-open-conns: 200
  conn-max-lifetime: 3600
service:
  tcp_port: 9090
  http_port: 9091
