mysql:
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: fsjs_sql_server
  username: root
  password: "root"
  path: 192.168.20.81
service:
  tcp_port: 9090
  http_port: 9096
cache:
  insert_count: 500
  query_count: 50000
